<a href="https://colab.research.google.com/github/Arun6793/Guvi-iitda-task1/blob/main/Numpy_tasks_A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a.size
a.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info

<function numpy.info>

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
b=np.zeros(10)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
c=np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
d=np.arange(0,9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
e=[1,2,0,0,4,0]
f=np.nonzero(e)
f

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
g=np.eye(3)
g

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
h=np.random.random((3,3,3))
h

array([[[0.68685387, 0.68816073, 0.86347683],
        [0.86385152, 0.36505754, 0.72090404],
        [0.8540353 , 0.86095756, 0.83392128]],

       [[0.44042531, 0.81609911, 0.57085375],
        [0.9838871 , 0.16487223, 0.14243034],
        [0.29409456, 0.39474164, 0.02993211]],

       [[0.29482346, 0.61818587, 0.70333423],
        [0.49072025, 0.53416627, 0.31835355],
        [0.55381673, 0.16103926, 0.13146711]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
i=np.random.random((10,10))
j=i.min(),i.max()
j

(0.029291111119710056, 0.9952419061390743)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
k=np.random.random(30)
l=k.mean()
l

0.5107614100277267

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
m=np.ones((5,5))
m[1:-1,1:-1]=0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
m=np.pad(m, pad_width=1, mode='constant', constant_values=0)
m

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
n=np.diag([0,1,2,3,4])
n

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 

*   List item
*   List item


(**hint**: array\[::2\])

In [ ]:
o = np.zeros((8,8),dtype=int)
o[1::2,::2] = 1
o[::2,1::2] = 1
print(o)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
p = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(p)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
i = np.random.random((5,5))
i = (i - np.mean (i)) / (np.std (i))
print(i)

[[-0.51547989  1.61222645 -1.08319418 -0.74940119  0.6212322 ]
 [-1.57879913  0.68225887 -0.20492791 -0.59064422 -1.14745386]
 [-0.9257097  -0.52651737  1.19418766 -0.42028488  1.96267907]
 [ 0.95398498  1.58805778 -0.6793384  -1.56906706  0.62069447]
 [-0.65871817  0.75310214 -0.44416329  0.87641549  0.22886014]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
t = np.dot(np.ones((5,3)), np.ones((3,2)))
print(t)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
h = np.arange(10)
h[(3 < h) & (h < 8)] *= -1
print(h)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


## `**bold text**#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)`

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+1.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+2.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+3.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+4.j, 0.+0.j]])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
m = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(m)),m))

[ -9. -10.  -4. -10.  -9.  -4.  -1.   3.   9.   1.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
j = np.random.randint(0,10,10)
k = np.random.randint(0,10,10)
print(np.intersect1d(j,k))

[0 2 3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

IndentationError: ignored

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
am= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(am)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[9. 6. 0. 0. 4. 2. 4. 0. 5. 9.]
[9. 6. 0. 0. 4. 2. 4. 0. 5. 9.]
[9. 6. 0. 0. 4. 2. 4. 0. 5. 9.]
[9 6 0 0 4 2 4 0 5 9]
[9. 6. 0. 0. 4. 2. 4. 0. 5. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
ak = np.zeros((5,5))
ak += np.arange(5)
ak


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
Z

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
Z

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
p = np.random.random(10)
p.sort()
p

array([0.09269333, 0.12967202, 0.1853784 , 0.24578696, 0.27504995,
       0.30274405, 0.43055622, 0.5132005 , 0.58140139, 0.81451106])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
t = np.arange(10)
np.add.reduce(t)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.array([5,2,4,6,4,5,5])
B = np.array([5,2,9,7,6,4,6])
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random ((10,2))
X, Y = Z [:, 0], Z [:, 1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.77672648 0.71493652 0.40729076 0.80548244 0.84299311 0.42699903
 0.49819873 1.04975459 0.73335258 0.29150421]
[0.7726086  0.66636042 0.37744219 1.43016223 1.45668316 0.7624775
 0.44431729 1.13179879 1.14525328 0.08325837]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
z = np.arange(10)
max(z)
print(z.argmax())
z[9] = 0
print(z)

9
[0 1 2 3 4 5 6 7 8 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print (np.linalg.det (C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

ValueError: ignored

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

80


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
('y', float, 1)]),
('color', [ ('r', float, 1),
('g', float, 1),
('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = arange (10)
Z = Z.astype
print (Z)

<built-in method astype of numpy.ndarray object at 0x7f457699c9e0>


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
J = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(J):
    print(index, value)
for index in np.ndindex(J.shape):
    print(index, J[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
A, B = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
C = np.sqrt(A*B+A*B)
sigma, mu = 1.0, 0.0
D = np.exp(-( (C-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(D)

[[0.36787944 0.45942582 0.57375342 0.71653131 0.89483932        nan
         nan        nan        nan        nan]
 [0.45942582 0.54610814 0.64914526 0.77162295 0.91720915        nan
         nan        nan        nan        nan]
 [0.57375342 0.64914526 0.73444367 0.83095039 0.9401382         nan
         nan        nan        nan        nan]
 [0.71653131 0.77162295 0.83095039 0.89483932 0.96364044        nan
         nan        nan        nan        nan]
 [0.89483932 0.91720915 0.9401382  0.96364044 0.98773022        nan
         nan        nan        nan        nan]
 [       nan        nan        nan        nan        nan 0.98773022
  0.96364044 0.9401382  0.91720915 0.89483932]
 [       nan        nan        nan        nan        nan 0.96364044
  0.89483932 0.83095039 0.77162295 0.71653131]
 [       nan        nan        nan        nan        nan 0.9401382
  0.83095039 0.73444367 0.64914526 0.57375342]
 [       nan        nan        nan        nan        nan 0.91720915
  0.77162295 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
A = np.random.rand(5, 10)
B = A-A.mean(axis=1, keepdims=True)
print(B)

[[ 0.57955088  0.17275658 -0.22731145 -0.17258094 -0.31606098 -0.17292639
  -0.33692509 -0.35847044  0.25747109  0.57449674]
 [ 0.38810442 -0.37689835 -0.42101888 -0.052156   -0.18228558 -0.27207125
   0.41847307  0.15254093  0.2984869   0.04682475]
 [-0.0523233  -0.27894082  0.27590975  0.34133368 -0.41841547 -0.1707178
   0.37450246 -0.04711466 -0.35530919  0.33107535]
 [ 0.07346969  0.27337826  0.09896498 -0.15645207 -0.22180747  0.54668647
  -0.38526965  0.18595264 -0.31924455 -0.0956783 ]
 [-0.03737367  0.00365053  0.11960723 -0.08766991  0.28242158  0.1518635
   0.0460346  -0.33578625  0.03196817 -0.17471578]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[4 6 8]
 [1 8 0]
 [4 0 7]]
[[4 0 7]
 [4 6 8]
 [1 8 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
A = np.random.uniform(0,1,10)
B = 0.5
X = A.flat[np.abs(A-B).argmin()]
print (X)

0.4597280184840332


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj,'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
np.add.at(Z, I, 1)
print(Z)

[5. 1. 9. 3. 3. 3. 5. 7. 5. 9.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
A = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
B = A[...,0]*(256*256) + A[...,1]*256 +A[...,2]
C = len(np.unique(B))
print (C)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[23 25 19 20 15 25 25 19 28 18 28 21 18 22 23 23]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
#1
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums/D_counts
print (D_means)

#2
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.37596172 0.47563917 0.55525904 0.47484781 0.3740643  0.38479773
 0.44086906 0.32351324 0.49805579 0.48877384]
0    0.375962
1    0.475639
2    0.555259
3    0.474848
4    0.374064
5    0.384798
6    0.440869
7    0.323513
8    0.498056
9    0.488774
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.97488333, 2.48719299, 1.41100555, 1.68672983, 1.00296078])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
A = np.roll(faces.repeat(2,axis=1),-1,axis=1)
A = A.reshape(len(A)*3,2)
A = np.sort(A,axis=1)
B = A.view( dtype=[('p0',A.dtype),('p1',A.dtype)])
B = np.unique(B)
print (B)

[( 7, 74) ( 7, 75) ( 8, 36) ( 8, 95) (10, 50) (10, 74) (11, 52) (11, 64)
 (13, 53) (13, 90) (15, 20) (15, 79) (16, 16) (16, 79) (20, 79) (32, 61)
 (32, 66) (36, 95) (50, 74) (52, 64) (53, 90) (54, 78) (54, 96) (59, 73)
 (59, 75) (61, 66) (73, 75) (74, 75) (78, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:]-ret[:-n]
    return ret[n-1:]/n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size-window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.47782182, -0.04953179,  0.6003413 ,  0.9239289 ,  0.45730107,
        0.32669392, -0.73351288, -0.55341602,  0.65572963,  0.51222477,
       -0.02951496, -0.38813248, -0.26793214,  0.69351777,  0.91733865,
       -0.91579474,  0.35515985,  0.56559186,  0.8236742 ,  0.2323934 ,
       -0.60373454, -0.49904597, -0.44954852, -0.6691737 ,  0.06984589,
       -0.83332068,  0.09861511,  0.62401916,  0.83503996,  0.01266084,
        0.51623332,  0.33455221, -0.70358931, -0.18614551, -0.94681651,
        0.14573686, -0.639036  ,  0.88215619, -0.04613632,  0.10477314,
        0.9513926 ,  0.92884749,  0.73086326, -0.07815125, -0.7251521 ,
        0.45147303,  0.31301011,  0.81659538, -0.70070062, -0.69797207,
       -0.00545578,  0.16872566, -0.87197671,  0.1293524 , -0.36254433,
       -0.72547258, -0.24303945,  0.84728248,  0.37182651,  0.93121914,
       -0.85330659, -0.09739155, -0.74747962, -0.71256755,  0.61032466,
        0.19712111, -0.95938627, -0.58103602,  0.16824456,  0.16

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1-P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[: ,1])/L
    U = U.reshape(len(U),1)
    D = P0 + U*T-p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[10.93777159  0.71705895  1.32468233  5.82397687  1.57840741 16.19500568
  2.7418855   5.60616864  9.43265995  8.51054435]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[11.79525291  2.41096217  7.41787296  4.28197439 10.65063836  0.49720029
   5.05043015  1.17377832  4.07308814  5.93040724]
 [ 3.57779036 13.7871397   7.92214909  6.28364932  2.70559518 16.25280051
   1.41501965 13.26051411  1.20227575  9.56214654]
 [16.80469027  2.19694451  7.3563458   3.53210979 12.59116055  1.16097262
   3.12957435  1.70664599  3.91409585  0.34640805]
 [ 7.73032093 14.3940928   5.88501509  9.59878854  0.2787174  14.52509223
   5.50679237  9.87726136  3.25855073 10.85710385]
 [ 2.81987887  0.76292473  1.09094583  8.53395437  2.93280157  6.33019241
  11.4171055   9.40362669 11.72471656  5.65784933]
 [ 8.80874935  4.44874654  1.21053156  0.51542511  5.37997866  6.91304576
   1.88648324  5.86794523  2.37569477  0.70955474]
 [ 5.44104948  1.03813995  1.45522965  5.04568901  4.20938562  6.2449936
   7.64750609  7.7074282   7.95558851  3.36904478]
 [ 5.68634408  6.65232863  2.05011049  0.6408735   1.99695734 10.09816619
   2.73687997  9.23616952  3.94148618  2.49608726]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
A = np.arange(1,15,dtype=np.uint32)
B = stride_tricks.as_strided(A,(11,4),(4,4))
print (B)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
A = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(A)
rank = np.sum(S> 1e-10)
print (rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
A = np.random.randint(0,10,50)
print (np.bincount(A).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[3 2 4]
   [2 0 4]
   [3 3 3]]

  [[2 4 0]
   [0 4 3]
   [3 3 3]]

  [[4 0 1]
   [4 3 3]
   [3 3 4]]

  [[0 1 3]
   [3 3 4]
   [3 4 2]]

  [[1 3 0]
   [3 4 4]
   [4 2 1]]

  [[3 0 3]
   [4 4 2]
   [2 1 1]]

  [[0 3 0]
   [4 2 1]
   [1 1 3]]

  [[3 0 3]
   [2 1 4]
   [1 3 0]]]


 [[[2 0 4]
   [3 3 3]
   [0 0 4]]

  [[0 4 3]
   [3 3 3]
   [0 4 4]]

  [[4 3 3]
   [3 3 4]
   [4 4 1]]

  [[3 3 4]
   [3 4 2]
   [4 1 1]]

  [[3 4 4]
   [4 2 1]
   [1 1 0]]

  [[4 4 2]
   [2 1 1]
   [1 0 0]]

  [[4 2 1]
   [1 1 3]
   [0 0 3]]

  [[2 1 4]
   [1 3 0]
   [0 3 4]]]


 [[[3 3 3]
   [0 0 4]
   [3 4 4]]

  [[3 3 3]
   [0 4 4]
   [4 4 3]]

  [[3 3 4]
   [4 4 1]
   [4 3 1]]

  [[3 4 2]
   [4 1 1]
   [3 1 1]]

  [[4 2 1]
   [1 1 0]
   [1 1 4]]

  [[2 1 1]
   [1 0 0]
   [1 4 1]]

  [[1 1 3]
   [0 0 3]
   [4 1 1]]

  [[1 3 0]
   [0 3 4]
   [1 1 0]]]


 [[[0 0 4]
   [3 4 4]
   [2 0 3]]

  [[0 4 4]
   [4 4 3]
   [0 3 4]]

  [[4 4 1]
   [4 3 1]
   [3 4 2]]

  [[4 1 1]
   [3 1 1]
   [4 2 4]]

  [[1 1 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
#1
A = np.arange(10000)
np.random.shuffle(A)
n = 5
print (A[np.argsort(A)[-n:]])

#2
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[[[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]

 [[1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  ...
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]
  [1. 1. 1. ... 1. 1. 1.]]]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand()
np.power(x,3)

0.4312983375833107

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[4]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
A = np.random.randint(0,5,(10,3))
print (Z)
B = np.all(A[:,1:] == A[:,:-1], axis=1)
C = A[~B]
print (C)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[[3 1 1]
 [2 2 3]
 [1 2 0]
 [1 4 2]
 [3 4 4]
 [0 4 4]
 [4 3 2]
 [1 1 0]
 [2 0 0]
 [1 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
A = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((A.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))
print ('A * B')
print (np.einsum('i,i->i', A, B))
print ('inner')
print (np.einsum('i,i', A, B))
print ('outer')
print (np.einsum('i,j->ij', A, B))

sum
3.908728660161929
A * B
[0.06045093 0.17102648 0.00555783 0.60190889 0.11165332 0.18344581
 0.39718453 0.21508745 0.00128756 0.32740272]
inner
2.0750055158196217
outer
[[6.04509287e-02 3.45908194e-02 4.79887925e-02 1.50252870e-01
  4.17508091e-02 4.36239906e-02 1.48870385e-01 1.23838369e-01
  2.39546280e-03 8.35869094e-02]
 [2.98885947e-01 1.71026484e-01 2.37269733e-01 7.42891337e-01
  2.06427434e-01 2.15688957e-01 7.36055956e-01 6.12290813e-01
  1.18438241e-02 4.13276572e-01]
 [7.00113618e-03 4.00614254e-03 5.55783143e-03 1.74015656e-02
  4.83537816e-03 5.05232104e-03 1.72414529e-02 1.43423651e-02
  2.77430995e-04 9.68063433e-03]
 [2.42164767e-01 1.38569877e-01 1.92241790e-01 6.01908887e-01
  1.67252600e-01 1.74756513e-01 5.96370693e-01 4.96093121e-01
  9.59615847e-03 3.34846873e-01]
 [1.61662658e-01 9.25055068e-02 1.28335427e-01 4.01818116e-01
  1.11653318e-01 1.16662728e-01 3.98120966e-01 3.31178368e-01
  6.40613620e-03 2.23534728e-01]
 [2.54205759e-01 1.45459891e-01 2.01800496e

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.21042484  0.19387699]
